url_embed.settings:
  type: mapping
  label: 'Url embed settings'
  mapping:
    file_scheme:
      type: string
      label: 'File scheme for buton images'
    upload_directory:
      type: string
      label: 'Upload directory for buton images'

url_embed.url_button.*:
  type: config_entity
  label: 'Url button config'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    button_label:
      type: string
      label: 'Button label'
    source:
      type: string
      label: 'Source of Url'
    source_type_bundles:
      type: sequence
      label: 'Entity type bundles'
      sequence:
        type: string
        label: 'Bundle'              
    Oembed_type:
      type: string
      label: 'Oembed Provider'
    button_icon_uuid:
      type: string
      label: 'Button image'
    display_plugins:
      type: sequence
      label: 'Allowed display plugins'
      sequence:
        type: string
        label: 'Display plugin'
